#############################################################################
# Makefile for building: mprisserv
# Generated by qmake (2.01a) (Qt 4.6.3) on: Sun Apr 17 10:29:31 2011
# Project:  mprisserv.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile mprisserv.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtDBus -I/usr/include/qt4 -I. -Iinclude -Iobj
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/lib64/qt4
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 -lQtDBus -L/usr/lib64 -L/usr/lib64/qt4 -lQtXml -lQtGui -L/usr/X11R6/lib -lQtNetwork -lQtCore -lgthread-2.0 -lrt -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = MprisServ.cpp \
		src/MprisConnection.cpp \
		src/MprisDetector.cpp \
		src/QHttpServer.cpp obj/moc_MprisConnection.cpp \
		obj/moc_QHttpServer.cpp
OBJECTS       = MprisServ.o \
		MprisConnection.o \
		MprisDetector.o \
		QHttpServer.o \
		moc_MprisConnection.o \
		moc_QHttpServer.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		mprisserv.pro
QMAKE_TARGET  = mprisserv
DESTDIR       = 
TARGET        = mprisserv

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mprisserv.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt4/libQtDBus.prl \
		/usr/lib64/qt4/libQtXml.prl \
		/usr/lib64/qt4/libQtCore.prl \
		/usr/lib64/qt4/libQtGui.prl \
		/usr/lib64/qt4/libQtNetwork.prl
	$(QMAKE) -unix -o Makefile mprisserv.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/dbusinterfaces.prf:
/usr/share/qt4/mkspecs/features/dbusadaptors.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt4/libQtDBus.prl:
/usr/lib64/qt4/libQtXml.prl:
/usr/lib64/qt4/libQtCore.prl:
/usr/lib64/qt4/libQtGui.prl:
/usr/lib64/qt4/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile mprisserv.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/mprisserv1.0.0 || $(MKDIR) .tmp/mprisserv1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/mprisserv1.0.0/ && $(COPY_FILE) --parents confdefs.h include/MprisConnection.hpp include/MprisDetector.hpp include/QHttpServer.hpp .tmp/mprisserv1.0.0/ && $(COPY_FILE) --parents MprisServ.cpp src/MprisConnection.cpp src/MprisDetector.cpp src/QHttpServer.cpp .tmp/mprisserv1.0.0/ && (cd `dirname .tmp/mprisserv1.0.0` && $(TAR) mprisserv1.0.0.tar mprisserv1.0.0 && $(COMPRESS) mprisserv1.0.0.tar) && $(MOVE) `dirname .tmp/mprisserv1.0.0`/mprisserv1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/mprisserv1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: obj/moc_MprisConnection.cpp obj/moc_QHttpServer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) obj/moc_MprisConnection.cpp obj/moc_QHttpServer.cpp
obj/moc_MprisConnection.cpp: include/MprisConnection.hpp
	/usr/bin/moc $(DEFINES) $(INCPATH) include/MprisConnection.hpp -o obj/moc_MprisConnection.cpp

obj/moc_QHttpServer.cpp: include/QHttpServer.hpp
	/usr/bin/moc $(DEFINES) $(INCPATH) include/QHttpServer.hpp -o obj/moc_QHttpServer.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

MprisServ.o: MprisServ.cpp include/MprisDetector.hpp \
		include/MprisConnection.hpp \
		include/QHttpServer.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MprisServ.o MprisServ.cpp

MprisConnection.o: src/MprisConnection.cpp include/MprisConnection.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MprisConnection.o src/MprisConnection.cpp

MprisDetector.o: src/MprisDetector.cpp include/MprisDetector.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MprisDetector.o src/MprisDetector.cpp

QHttpServer.o: src/QHttpServer.cpp include/QHttpServer.hpp \
		include/MprisConnection.hpp \
		include/MprisDetector.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QHttpServer.o src/QHttpServer.cpp

moc_MprisConnection.o: obj/moc_MprisConnection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MprisConnection.o obj/moc_MprisConnection.cpp

moc_QHttpServer.o: obj/moc_QHttpServer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QHttpServer.o obj/moc_QHttpServer.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

